"""
upload_to_huggingface.py
========================

Upload trained SAM3TrackerModel checkpoints from this thesis to a
HuggingFace model repository, with a model card that documents the
training, evaluation, and intended use.

What gets uploaded:
  - best_by_iou.pth  (deployed checkpoint, epoch 23, val IoU 0.7143)
  - best_by_loss.pth (alternative checkpoint, epoch 16, val loss 0.3385)
  - RUN_INFO.md / loss_iou_curve.png if present (training metadata)
  - README.md         (model card, generated by this script)
  - config.json       (lightweight config for downstream loaders)

Optional: ablation runs (no-IoU loss, generic baseline) under
separate subfolders within the repo.

PREREQUISITES
-------------
1.  pip install huggingface_hub
2.  huggingface-cli login
    (or: export HF_TOKEN=<your token> in the environment)
3.  Create the repo at https://huggingface.co/new (or let this script
    create it with --create-repo).

USAGE
-----

Upload only the production run:

    python3 upload_to_huggingface.py \\
        --repo-id YOUR_USERNAME/medical-annotation-removal \\
        --production-run /home/ahma/.../runs/2026-04-19_16-03-50_v6_arrow_pca_axis_freeform_mask \\
        --create-repo

Upload production + ablations as subfolders:

    python3 upload_to_huggingface.py \\
        --repo-id YOUR_USERNAME/medical-annotation-removal \\
        --production-run /path/to/2026-04-19_16-03-50_v6_arrow_pca_axis_freeform_mask \\
        --ablation-run no-iou:/path/to/2026-05-07_15-24-52_v6_ablation_no_iou_loss \\
        --ablation-run generic-baseline:/path/to/2026-05-17_12-37-43_v6_arrow_pca_axis_freeform_mask
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

try:
    from huggingface_hub import HfApi, create_repo, upload_file, upload_folder
except ImportError:
    print("This script requires huggingface_hub. Install it with:")
    print("    pip install huggingface_hub")
    sys.exit(1)


MODEL_CARD = """\
---
license: mit
language:
  - en
library_name: pytorch
tags:
  - medical-imaging
  - segmentation
  - inpainting
  - sam
  - sam3-tracker
  - annotation-removal
  - thesis
base_model: facebook/sam2-hiera-large
pipeline_tag: image-segmentation
---

# Medical Annotation Removal Pipeline

Fine-tuned SAM3TrackerModel checkpoint and supporting artefacts from the
M.Sc. thesis
**"Bridging the Annotation Distribution Gap in Medical Imaging:
A Three-Stage Pipeline for Automated Detection, Segmentation,
and Removal of Visual Annotations from Medical Educational Imagery."**

Technical University of Munich, M.Sc. Data Engineering and Analytics, 2026.

## What this model does

Given an annotated educational image (an arrow, glyph, or freeform
contour drawn over an underlying object) and a type-specific geometric
prompt derived from the annotation mask, the model predicts a
per-instance binary segmentation of the underlying object that the
annotation refers to.

The predicted object mask drives Stage 3 of the full pipeline (FLUX.1
Fill inpainting), which removes the annotation while preserving the
underlying scene.

## Files in this repository

| File | Description |
|---|---|
| `best_by_iou.pth` | **Production checkpoint** &mdash; epoch 23, val IoU 0.7143. The model deployed for downstream inference. |
| `best_by_loss.pth` | Alternative checkpoint &mdash; epoch 16, val loss 0.3385. Use if you prefer best-by-loss selection. |
| `RUN_INFO.md` | Training metadata snapshot. |
| `loss_iou_curve.png` | Training curves. |
| `config.json` | Lightweight metadata for downstream loaders. |

## Architecture

| Property | Value |
|---|---|
| Base model | SAM3TrackerModel (Hiera vision encoder, video-pretrained on SA-V) |
| Total parameters | 458 M |
| Frozen parameters | 454 M (vision encoder) |
| Trainable parameters | **4.2 M (0.9 %)** &mdash; prompt encoder + mask decoder only |
| Precision | bfloat16 |

## Training

| Property | Value |
|---|---|
| Dataset | In-house, 9,964 source images expanded to 82,875 annotated samples |
| Annotation classes | arrow (25 %), number/letter (25 %), freeform_bbox (50 %) |
| Split | 80 / 10 / 10 train/val/test, stratified by source image |
| Optimizer | AdamW |
| Learning rate | 5e-5 |
| Weight decay | 1e-4 |
| Batch size | 48 |
| Epochs | 30 |
| Loss | 20 \u00b7 focal + Dice + IoU-MSE |
| Hardware | Single NVIDIA A40 (48 GB), bfloat16 |
| Wall-clock | ~12 hours |

## Headline results on the held-out test split (N = 8,288)

| Metric | Value |
|---|---|
| Micro IoU | **0.7086** |
| Boundary F1 (2 px tol) | **0.7628** |

Per-class breakdown:

| Class | N | IoU | Boundary F1 |
|---|---:|---:|---:|
| Arrow | 2,080 | 0.6543 | 0.6882 |
| Freeform bbox | 4,141 | 0.7664 | 0.8523 |
| Number / Letter | 2,067 | 0.6475 | 0.6585 |

## Type-specific prompt routing

The model is trained with a routing scheme that derives a different
geometric prompt for each annotation class:

| Class | Prompt |
|---|---|
| Arrow | Single point at the arrow tip (extracted via PCA on the annotation mask) |
| Number / Letter | Stratified samples of points on the glyph mask |
| Freeform bbox | Filled-contour dense mask of the freeform outline |

Under a paired comparison against a baseline that forces every
annotation through a generic uniform box prompt (N = 5,531 identical
basenames), type-specific routing yields:

| Metric | Production | Generic | &Delta; |
|---|---:|---:|---:|
| IoU | 0.7226 | 0.6860 | **+3.66 pp** |
| Boundary F1 | 0.7614 | 0.6946 | **+6.68 pp** |

The Boundary F1 gap is 1.83x the IoU gap, and the asymmetry ratio is
preserved within every class (arrow 1.83x, freeform 1.80x,
number-or-letter 2.07x). This is the empirical signature that
type-specific routing recovers boundary-aligned segmentation signal
that uniform routing loses.

## Intended use and limitations

**Intended use.** Research on automated cleanup of annotated educational
medical imagery for downstream training-data construction (medical
vision-language models). The pipeline architecture and per-stage error
attribution methodology are reusable in adjacent settings that share
the same structural pattern (heterogeneous overlay-style annotations
on natural images).

**Limitations.**
- The evaluation is on a non-clinical proxy dataset that is
  structurally representative of the medical-annotation problem but is
  not clinical radiology. Absolute accuracy on clinical imagery
  remains to be established and is the principal direction for future
  work.
- All metrics are from a single training seed.
- The full pipeline (Pipeline B) shows a class-asymmetric cost when
  ground-truth annotation masks are replaced with predictions from
  GroundedSAM 2: the freeform class degrades by a factor of 4.7x on
  FID due to a stage-coupling failure in which SAM 2's mask refinement
  returns the object enclosed by the contour rather than the contour
  itself. This is the binding constraint identified by the thesis and
  the proposed fix lives upstream of this checkpoint (in the detection
  stage).

## Inference example

```python
import torch
from sam3_tracker_model import SAM3TrackerModel  # your local loader

# Load
model = SAM3TrackerModel.from_pretrained("facebook/sam2-hiera-large")
ckpt = torch.load("best_by_iou.pth", map_location="cpu")
model.load_state_dict(ckpt["model"], strict=False)
model.eval().to("cuda")

# Type-specific prompt routing (sketch)
# See repository: github.com/USERNAME/medical-annotation-removal
#   /inference/inference_zeroshot_pcs.py for the full prompt-derivation
#   logic per annotation type.
```

## Citation

```bibtex
@mastersthesis{{your_thesis_2026,
  title  = {{Bridging the Annotation Distribution Gap in Medical Imaging}},
  author = {{Your Name}},
  school = {{Technical University of Munich}},
  year   = {{2026}},
  type   = {{M.Sc. Thesis}}
}}
```

## Source code

Full pipeline source at:
👉 <https://github.com/USERNAME/medical-annotation-removal>

## License

This checkpoint is released under the MIT License. Note that it derives
from publicly available foundation models (SAM 2 / SAM 3 Tracker,
Hiera) &mdash; please check the upstream licences of those models before
any commercial use.

---

*Generated by `upload_to_huggingface.py` on {timestamp}.*
"""


def make_config_json(production_run_name, val_iou, val_loss):
    return {
        "architecture": "SAM3TrackerModel",
        "base_model": "facebook/sam2-hiera-large",
        "task": "image-segmentation",
        "framework": "pytorch",
        "precision": "bfloat16",
        "total_parameters": 458_000_000,
        "frozen_parameters": 454_000_000,
        "trainable_parameters": 4_200_000,
        "trainable_fraction": 0.009,
        "training": {
            "optimizer": "AdamW",
            "learning_rate": 5e-5,
            "weight_decay": 1e-4,
            "batch_size": 48,
            "epochs": 30,
            "loss": "20 * focal + Dice + IoU-MSE",
            "hardware": "single NVIDIA A40 48GB",
        },
        "evaluation": {
            "test_n": 8288,
            "micro_iou": 0.7086,
            "boundary_f1": 0.7628,
            "per_class": {
                "arrow":         {"n": 2080, "iou": 0.6543, "bf1": 0.6882},
                "freeform_bbox": {"n": 4141, "iou": 0.7664, "bf1": 0.8523},
                "number_letter": {"n": 2067, "iou": 0.6475, "bf1": 0.6585},
            },
            "best_by_iou":  {"epoch": 23, "val_iou":  val_iou},
            "best_by_loss": {"epoch": 16, "val_loss": val_loss},
        },
        "production_run_id": production_run_name,
        "annotation_classes": ["arrow", "freeform_bbox", "number_letter"],
        "type_specific_prompts": {
            "arrow":         "single point at arrow tip (PCA-derived)",
            "number_letter": "stratified points on glyph mask",
            "freeform_bbox": "filled-contour dense mask",
        },
    }


def upload_run(api, repo_id, run_dir, subfolder=None, ckpts_to_upload=None,
               include_curves=True, include_run_info=True):
    """Upload checkpoint(s) and metadata from a run directory."""
    run_dir = Path(run_dir)
    if not run_dir.is_dir():
        print(f"  SKIP: not a directory: {run_dir}")
        return

    if ckpts_to_upload is None:
        ckpts_to_upload = ["best_by_iou.pth", "best_by_loss.pth"]

    files_to_upload = []
    for ckpt in ckpts_to_upload:
        p = run_dir / ckpt
        if p.exists():
            files_to_upload.append(p)
        else:
            print(f"  warning: {ckpt} not found in {run_dir.name}")
    if include_curves:
        for png in ("loss_iou_curve.png", "loss_curve.png"):
            p = run_dir / png
            if p.exists():
                files_to_upload.append(p)
                break
    if include_run_info:
        p = run_dir / "RUN_INFO.md"
        if p.exists():
            files_to_upload.append(p)

    for src in files_to_upload:
        path_in_repo = src.name if subfolder is None else f"{subfolder}/{src.name}"
        print(f"  uploading {src.name:30s} -> {path_in_repo}")
        upload_file(
            path_or_fileobj=str(src),
            path_in_repo=path_in_repo,
            repo_id=repo_id,
            repo_type="model",
        )


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo-id", required=True,
                    help="HuggingFace repo (e.g., username/medical-annotation-removal)")
    ap.add_argument("--production-run", required=True,
                    help="path to the production-run directory (the one whose "
                         "best_by_iou.pth is the deployed checkpoint)")
    ap.add_argument("--ablation-run", action="append", default=[],
                    help="extra runs in 'name:/path' form; uploaded under that "
                         "subfolder in the repo. May be repeated.")
    ap.add_argument("--create-repo", action="store_true",
                    help="create the repo first (use once on first upload)")
    ap.add_argument("--private", action="store_true",
                    help="create the repo as private (default: public)")
    ap.add_argument("--val-iou", type=float, default=0.7143,
                    help="best val IoU to record in config.json")
    ap.add_argument("--val-loss", type=float, default=0.3385,
                    help="best val loss to record in config.json")
    args = ap.parse_args()

    api = HfApi()
    try:
        whoami = api.whoami()
        print(f"Authenticated as: {whoami['name']}")
    except Exception as e:
        print("Not authenticated to HuggingFace. Run `huggingface-cli login` "
              "or set HF_TOKEN.")
        print(f"  underlying error: {e}")
        sys.exit(1)

    # Create repo if asked
    if args.create_repo:
        print(f"\nCreating repo {args.repo_id} ({'private' if args.private else 'public'})...")
        create_repo(
            repo_id=args.repo_id,
            repo_type="model",
            private=args.private,
            exist_ok=True,
        )

    # Upload production run at the repo root
    production_run = Path(args.production_run)
    print(f"\nUploading production run: {production_run}")
    upload_run(api, args.repo_id, production_run, subfolder=None)

    # Upload ablation runs under named subfolders
    for spec in args.ablation_run:
        if ":" not in spec:
            print(f"  malformed --ablation-run '{spec}'; expected 'name:/path'")
            continue
        name, path = spec.split(":", 1)
        print(f"\nUploading ablation '{name}': {path}")
        upload_run(api, args.repo_id, path, subfolder=name)

    # Generate and upload config.json + README.md
    print("\nGenerating model card and config...")
    config = make_config_json(production_run.name, args.val_iou, args.val_loss)

    # write locally, then upload
    tmp_config = Path("/tmp/_hf_config.json")
    tmp_readme = Path("/tmp/_hf_README.md")
    tmp_config.write_text(json.dumps(config, indent=2))
    tmp_readme.write_text(MODEL_CARD.format(
        timestamp=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")))

    print("  uploading config.json")
    upload_file(path_or_fileobj=str(tmp_config),
                path_in_repo="config.json",
                repo_id=args.repo_id, repo_type="model")
    print("  uploading README.md (model card)")
    upload_file(path_or_fileobj=str(tmp_readme),
                path_in_repo="README.md",
                repo_id=args.repo_id, repo_type="model")

    print(f"\nDone. View at https://huggingface.co/{args.repo_id}")


if __name__ == "__main__":
    main()
